#title: Olasunkanmi Aremu - Data Scientist Portfolio
#logo: /assets/OLASUNKANMI_HEADSHOT.png
#description: Data Analyst | Python | SQL | AWS | Snowflake | MATLAB
#show_downloads: false
theme: jekyll-theme-cayman
