title: Olasunkanmi Aremu
logo: /assets/OLASUNKANMI_HEADSHOT.png
description: Welcome to my creative world! Explore my projects and journey in data analytics.
show_downloads: true
theme: jekyll-theme-cayman

# Customize colors
colors:
  primary: "#023046"
  text: "#333"
  background: "#D9F2F9"
  link: "#2D6DC2"  # Adjusted link color

# Add social media links
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/olasunkanmiaremu
  - title: Twitter
    url: https://twitter.com/your_twitter_handle

# Add custom CSS
sass:
  style: compressed
  include_paths:
    - _sass

# Configure navigation menu
navbar_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog

# Customize title font size
title-font-size: 2rem  # Adjust the value as needed
